/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HistoryWindow.java
 *
 * Created on 19.10.2011, 10:22:45
 */
package com.conarhco.torrent.se;

import java.io.File;
import java.util.Timer;

/**
 *
 * @author dprokopiuk
 */
public class HistoryWindow extends javax.swing.JFrame {

    /** Creates new form HistoryWindow */
    private final File TORRENT_SE_ACTIVITY = new File(System.getProperty("java.io.tmpdir") + "/torrent_se_acivity.log");
    private final File TORRENT_SE_ERROR = new File(System.getProperty("java.io.tmpdir") + "/torrent_se_error.log");
    private final long PING_DELAY = 3000;
    private Timer t;
    private LogTask historyTask;
    private LogTask errorTask;

    public HistoryWindow(Timer t) {
        this.t = t;
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();

        setTitle("History");
        setMinimumSize(new java.awt.Dimension(600, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        historyArea.setColumns(20);
        historyArea.setEditable(false);
        jScrollPane1.setViewportView(historyArea);

        jTabbedPane1.addTab("Info", jScrollPane1);

        errorArea.setColumns(20);
        errorArea.setEditable(false);
        errorArea.setRows(5);
        jScrollPane2.setViewportView(errorArea);

        jTabbedPane1.addTab("Errors", jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        historyTask = new LogTask(historyArea, TORRENT_SE_ACTIVITY);
        errorTask = new LogTask(errorArea, TORRENT_SE_ERROR);
        t.scheduleAtFixedRate(historyTask, 0, PING_DELAY);
        t.scheduleAtFixedRate(errorTask, 0, PING_DELAY);
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        historyTask.cancel();
        errorTask.cancel();
    }//GEN-LAST:event_formComponentHidden
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JTextArea errorArea = new javax.swing.JTextArea();
    public final javax.swing.JTextArea historyArea = new javax.swing.JTextArea();
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}

